In [12]:
import pandas as pd
import numpy as np

In [13]:
df = (
    pd.read_csv(
        "./datasets/ASSIST2009/skill_builder_data.csv",
        encoding="Windows-1252",
        low_memory=False,
    )
    .dropna(subset=["skill_name"])
    .drop_duplicates(subset=["order_id", "skill_name"])
    .sort_values(by=["order_id"])
)
df

order_id  assignment_id  user_id  assistment_id  problem_id  original  \
337244  20224085         232368    73963          42904       76429         0   
337245  20224095         232368    73963          42904       76430         0   
337246  20224113         232368    73963          42904       76431         0   
337247  20224123         232368    73963          42904       76432         0   
337248  20224142         232368    73963          42904       76433         0   
...          ...            ...      ...            ...         ...       ...   
19381   38310200         290668    96282          73176      135601         1   
59154   38310201         290668    96282          73177      135602         1   
19382   38310201         290668    96282          73177      135602         1   
55227   38310202         290668    96282          73191      135616         1   
19383   38310202         290668    96282          73191      135616         1   

        correct  attempt_count  ms_first_response tutor_mode  ... hint_count  \
337244        0              3             106016      tutor  ...          0   
337245        1              1             194187      tutor  ...          0   
337246        1              1              12734      tutor  ...          0   
337247        1              1             333484      tutor  ...          0   
337248        0              2              52828      tutor  ...          2   
...         ...            ...                ...        ...  ...        ...   
19381         1              1               5230      tutor  ...          0   
59154         1              1               5532      tutor  ...          0   
19382         1              1               5532      tutor  ...          0   
55227         1              1               7910      tutor  ...          0   
19383         1              1               7910      tutor  ...          0   

        hint_total  overlap_time  template_id answer_id  answer_text  \
337244           0        112313        31690  128739.0          NaN   
337245           0        194187        31690  128742.0          NaN   
337246           2         12734        31690       NaN           35   
337247           1        333484        31690  128750.0          NaN   
337248           2         65203        31690       NaN          2.5   
...            ...           ...          ...       ...          ...   
19381            2          5230        63443       NaN           30   
59154            2          5532        63443       NaN           30   
19382            2          5532        63443       NaN           30   
55227            2          7910        63444       NaN           42   
19383            2          7910        63444       NaN           42   

        first_action bottom_hint  opportunity  opportunity_original  
337244             0         NaN            1                   NaN  
337245             0         NaN            2                   NaN  
337246             0         NaN            3                   NaN  
337247             0         NaN            4                   NaN  
337248             0         1.0            5                   NaN  
...              ...         ...          ...                   ...  
19381              0         NaN            9                   9.0  
59154              0         NaN           13                  13.0  
19382              0         NaN           10                  10.0  
55227              0         NaN            3                   3.0  
19383              0         NaN           11                  11.0  

[325637 rows x 30 columns]

In [14]:
u_list = np.unique(df["user_id"].values)
u_list, len(u_list)

(array([   14, 21825, 51950, ..., 96297, 96298, 96299]), 4151)

In [15]:
q_list = np.unique(df["skill_name"].values)
q_list, len(q_list)

(array(['Absolute Value', 'Addition Whole Numbers',
        'Addition and Subtraction Fractions',
        'Addition and Subtraction Integers',
        'Addition and Subtraction Positive Decimals',
        'Algebraic Simplification', 'Algebraic Solving',
        'Angles - Obtuse, Acute, and Right',
        'Angles on Parallel Lines Cut by a Transversal', 'Area Circle',
        'Area Irregular Figure', 'Area Parallelogram', 'Area Rectangle',
        'Area Trapezoid', 'Area Triangle', 'Box and Whisker',
        'Calculations with Similar Figures',
        'Choose an Equation from Given Information', 'Circle Graph',
        'Circumference ', 'Complementary and Supplementary Angles',
        'Computation with Real Numbers', 'Congruence',
        'Conversion of Fraction Decimals Percents', 'Counting Methods',
        'D.4.8-understanding-concept-of-probabilities',
        'Distributive Property', 'Divisibility Rules',
        'Division Fractions',
        'Effect of Changing Dimensions of a 

In [16]:
u2idx = {u: idx for idx, u in enumerate(u_list)}
q2idx = {q:idx for idx, q in enumerate(q_list)}
u2idx, q2idx

({14: 0,
  21825: 1,
  51950: 2,
  52613: 3,
  53167: 4,
  54318: 5,
  58161: 6,
  64525: 7,
  64531: 8,
  64532: 9,
  64535: 10,
  64550: 11,
  64634: 12,
  69931: 13,
  70190: 14,
  70363: 15,
  70657: 16,
  70676: 17,
  70677: 18,
  70679: 19,
  70682: 20,
  70684: 21,
  70687: 22,
  70688: 23,
  70692: 24,
  70693: 25,
  70695: 26,
  70699: 27,
  70701: 28,
  70702: 29,
  70704: 30,
  70706: 31,
  70707: 32,
  70708: 33,
  70709: 34,
  70727: 35,
  70728: 36,
  70729: 37,
  70730: 38,
  70731: 39,
  70732: 40,
  70733: 41,
  70734: 42,
  70736: 43,
  70740: 44,
  70743: 45,
  70744: 46,
  70745: 47,
  70746: 48,
  70748: 49,
  70750: 50,
  70752: 51,
  70754: 52,
  70756: 53,
  70758: 54,
  70759: 55,
  70816: 56,
  70872: 57,
  70874: 58,
  71034: 59,
  71066: 60,
  71068: 61,
  71091: 62,
  71105: 63,
  71113: 64,
  71144: 65,
  71146: 66,
  71148: 67,
  71151: 68,
  71152: 69,
  71163: 70,
  71173: 71,
  71174: 72,
  71175: 73,
  71176: 74,
  71177: 75,
  71179: 76,
  71180: 77,

In [17]:
q_seqs = []
r_seqs = []
ms_seqs = []

In [18]:
for u in u_list:
    df_u = df[df["user_id"] == u]
    q_seq = np.array([q2idx[q] for q in df_u["skill_name"]])
    r_seq = df_u["correct"].values
    ms_seq = df_u["ms_first_response"].values
    r_seqs.append(r_seq)
    q_seqs.append(q_seq)
    ms_seqs.append(ms_seq)

In [8]:
q_seqs[0], r_seqs[0], ms_seqs[0]

(array([67, 18, 67, 18, 67, 18, 18, 67, 67, 18, 18, 67, 32, 35, 18, 32, 18,
        74, 32, 18, 32, 18, 74, 32, 18, 32, 35, 18, 49, 77, 77, 49, 77, 49,
        49]),
 array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([26271, 26271, 29123, 29123, 13779, 13779, 16901, 16901, 11079,
        11079,  8244,  8244, 21884, 21884, 21884, 59891, 59891, 59891,
        64234, 64234, 82572, 82572, 82572, 30678, 30678, 27225, 27225,
        27225,  9236, 11635, 11012,  3426, 11417, 11915,  2212]))

In [9]:
proc_q_seqs = []
proc_r_seqs = []
seq_len = 100

In [10]:
for q_seq, r_seq in zip(q_seqs, r_seqs):
    i = 0
    print(q_seq)
    print(r_seq)
    while i + seq_len + 1 < len(q_seq):
        proc_q_seqs.append(q_seq[i : i + seq_len + 1])
        proc_r_seqs.append(r_seq[i : i + seq_len + 1])
        i += seq_len + 1
    proc_q_seqs.append(
        np.concatenate([q_seq[i:], np.array([-1] * (i + seq_len + 1 - len(q_seq)))])
    )
    proc_r_seqs.append(
        np.concatenate([r_seq[i:], np.array([-1] * (i + seq_len + 1 - len(q_seq)))])
    )
    break

proc_q_seqs, proc_r_seqs

[67 18 67 18 67 18 18 67 67 18 18 67 32 35 18 32 18 74 32 18 32 18 74 32
 18 32 35 18 49 77 77 49 77 49 49]
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0]


([array([67, 18, 67, 18, 67, 18, 18, 67, 67, 18, 18, 67, 32, 35, 18, 32, 18,
         74, 32, 18, 32, 18, 74, 32, 18, 32, 35, 18, 49, 77, 77, 49, 77, 49,
         49, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])],
 [array([ 0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  1,  1,  0,  0,  0,  1,  1,  0,  0,  0,  0,  1,  1,  0,  1,  0,
          0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])])

In [11]:
len(proc_q_seqs[0]), len(proc_r_seqs[0])

(101, 101)